image: Ubuntu
stack: jdk 11
branches:
  only:
    - master
build: off
install:
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew test -D
before_test:
    -chromedriver.ext --version
build_script:
  - ./gradlew test --info
